# -*- coding: utf-8 -*-
"""
Visualización del dataset METABRIC

Autor: Francisco Mora

Proyecto de análisis visual de supervivencia,
recaída y perfiles de pacientes con cáncer de mama.

Asignatura:
Fundamentos de Modelado Orientado a Datos
"""

"""Practica_visualización_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lPYd0d652zxjcnGqXAxScA73NYS5EtHl

# Practica 2 Visualización de datos
Nombre: Francisco Mora

## 1. Carga de datos
"""

import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# =========================
# 1. Cargar datos
# =========================

df = pd.read_csv("Breast Cancer METABRIC.csv")

# Carpeta de salida
os.makedirs("graficas_metabric", exist_ok=True)
os.makedirs("tablas_metabric", exist_ok=True)

# Estilo general
sns.set_theme(style="whitegrid")

"""## 2. Limpieza de los datos"""

# =========================
# 2. Limpieza básica
# =========================

numeric_cols = [
    "Age at Diagnosis",
    "Tumor Stage",
    "Tumor Size",
    "Mutation Count",
    "Overall Survival (Months)",
    "Relapse Free Status (Months)",
    "Neoplasm Histologic Grade",
    "Lymph nodes examined positive",
    "Nottingham prognostic index"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

"""## 3. Gráficas

"""

# =========================
# 3. Función para guardar
# =========================

def guardar(nombre):
    plt.tight_layout()
    plt.savefig(f"graficas_metabric/{nombre}.png", dpi=300, bbox_inches="tight")
    plt.show()

"""## 3.1. Gráfica de la edad

"""

# =========================
# GRÁFICA 1: Edad
# =========================

plt.figure(figsize=(9, 5))
sns.histplot(df["Age at Diagnosis"].dropna(), bins=30, kde=True)
plt.title("Distribución de la edad al diagnóstico")
plt.xlabel("Edad al diagnóstico")
plt.ylabel("Número de pacientes")
guardar("01_distribucion_edad")

"""## 3.2. Gráfica de los subtipos de la variable "PAM50"
"""

# =========================
# GRÁFICA 2: Subtipos PAM50
# =========================

plt.figure(figsize=(10, 6))
sns.countplot(
    data=df,
    y="Pam50 + Claudin-low subtype",
    order=df["Pam50 + Claudin-low subtype"].value_counts().index
)
plt.title("Distribución de pacientes según subtipo molecular")
plt.xlabel("Número de pacientes")
plt.ylabel("Subtipo molecular")
guardar("02_subtipos_pam50")

"""## 3.3. Gráfica de los estadios tumorales"""

# =========================
# GRÁFICA 3: Estadios tumorales
# =========================

plt.figure(figsize=(8, 5))
sns.countplot(
    data=df,
    x="Tumor Stage",
    order=sorted(df["Tumor Stage"].dropna().unique())
)
plt.title("Distribución de pacientes según estadio tumoral")
plt.xlabel("Estadio tumoral")
plt.ylabel("Número de pacientes")
guardar("03_estadio_tumoral")

"""## 3.4. Gráfica relacionando la supervivencia según estadio"""

# =========================
# GRÁFICA 4: Supervivencia según estadio
# =========================

plt.figure(figsize=(8, 6))
sns.boxplot(
    data=df,
    x="Tumor Stage",
    y="Overall Survival (Months)"
)
plt.title("Supervivencia global según estadio tumoral")
plt.xlabel("Estadio tumoral")
plt.ylabel("Supervivencia global (meses)")
guardar("04_supervivencia_por_estadio")

"""## 3.5. Gráfica relacionando supervivencia según subtipo molecular"""

# =========================
# GRÁFICA 5: Supervivencia según subtipo molecular
# =========================

plt.figure(figsize=(12, 6))
sns.boxplot(
    data=df,
    x="Pam50 + Claudin-low subtype",
    y="Overall Survival (Months)"
)
plt.title("Supervivencia global según subtipo molecular")
plt.xlabel("Subtipo molecular")
plt.ylabel("Supervivencia global (meses)")
plt.xticks(rotation=45)
guardar("05_supervivencia_por_pam50")

"""## 3.6. Gráfica relacionando la recaida según estadio tumoral"""

# =========================
# GRÁFICA 6: Recaída según estadio tumoral
# =========================

tabla_recaida_estadio = pd.crosstab(
    df["Tumor Stage"],
    df["Relapse Free Status"],
    normalize="index"
) * 100

tabla_recaida_estadio.plot(
    kind="bar",
    stacked=True,
    figsize=(8, 6)
)

plt.title("Porcentaje de recaída según estadio tumoral")
plt.xlabel("Estadio tumoral")
plt.ylabel("Porcentaje de pacientes")
plt.legend(title="Estado de recaída")
guardar("06_recaida_por_estadio")

"""## 3.7. Gráfica (heatmap) relacionando PAM50 y recaída"""

# =========================
# GRÁFICA 7: Heatmap PAM50 vs recaída
# =========================

heatmap_data = pd.crosstab(
    df["Pam50 + Claudin-low subtype"],
    df["Relapse Free Status"],
    normalize="index"
) * 100

plt.figure(figsize=(8, 6))
sns.heatmap(
    heatmap_data,
    annot=True,
    fmt=".1f",
    cmap="Reds"
)
plt.title("Porcentaje de recaída por subtipo molecular")
plt.xlabel("Estado de recaída")
plt.ylabel("Subtipo molecular")
guardar("07_heatmap_pam50_recaida")

"""## 3.8. Gráfica relacionando mutation count y supervivencia"""

# =========================
# GRÁFICA 8: Mutation Count vs supervivencia
# =========================

fig = px.scatter(
    df,
    x="Mutation Count",
    y="Overall Survival (Months)",
    color="Relapse Free Status",
    hover_data=[
        "Age at Diagnosis",
        "Tumor Stage",
        "Pam50 + Claudin-low subtype",
        "Overall Survival Status"
    ],
    title="Relación entre carga mutacional y supervivencia"
)

fig.write_html("graficas_metabric/08_mutation_count_supervivencia.html")
fig.show()

"""## 3.9. Gráfica relacionando edad y supervivencia"""

# =========================
# GRÁFICA 9: Edad vs supervivencia
# =========================

fig = px.scatter(
    df.dropna(subset=["Tumor Size"]),
    x="Age at Diagnosis",
    y="Overall Survival (Months)",
    color="Overall Survival Status",
    size="Tumor Size",
    hover_data=[
        "Tumor Stage",
        "Pam50 + Claudin-low subtype",
        "Relapse Free Status"
    ],
    title="Relación entre edad, supervivencia y estado vital"
)

fig.write_html("graficas_metabric/09_edad_supervivencia.html")
fig.show()

"""## 3.10. Gráfica relacionando tamaño tumoral según recaída"""

# =========================
# GRÁFICA 10: Tamaño tumoral según recaída
# =========================

plt.figure(figsize=(8, 6))
sns.boxplot(
    data=df,
    x="Relapse Free Status",
    y="Tumor Size"
)
plt.title("Tamaño tumoral según estado de recaída")
plt.xlabel("Estado de recaída")
plt.ylabel("Tamaño tumoral")
guardar("10_tamano_tumoral_recaida")

"""## 3.11. Gráfica de los receptores hormonales"""

# =========================
# GRÁFICA 11: Receptores hormonales
# =========================

fig, axes = plt.subplots(1, 3, figsize=(15, 5))

sns.countplot(data=df, x="ER Status", ax=axes[0])
axes[0].set_title("Estado ER")

sns.countplot(data=df, x="PR Status", ax=axes[1])
axes[1].set_title("Estado PR")

sns.countplot(data=df, x="HER2 Status", ax=axes[2])
axes[2].set_title("Estado HER2")

plt.suptitle("Distribución de receptores hormonales")
plt.tight_layout()
plt.savefig("graficas_metabric/11_receptores_hormonales.png", dpi=300, bbox_inches="tight")
plt.show()

"""## 3.12. Gráfica relacionando el nottingham index vs supervivencia"""

# =========================
# GRÁFICA 12: Nottingham index vs supervivencia
# =========================

fig = px.scatter(
    df,
    x="Nottingham prognostic index",
    y="Overall Survival (Months)",
    color="Relapse Free Status",
    hover_data=[
        "Tumor Stage",
        "Tumor Size",
        "Pam50 + Claudin-low subtype"
    ],
    title="Índice pronóstico de Nottingham y supervivencia"
)

fig.write_html("graficas_metabric/12_nottingham_supervivencia.html")
fig.show()

"""## 3.13. Gráfica hacienndo un clustering visual con PCA"""

# =========================
# GRÁFICA 13: Clustering visual con PCA
# =========================

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

vars_cluster = [
    "Age at Diagnosis",
    "Tumor Stage",
    "Tumor Size",
    "Mutation Count",
    "Nottingham prognostic index"
]

df_cluster = df[vars_cluster].dropna()

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_cluster)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
clusters = kmeans.fit_predict(X_scaled)

df_pca = pd.DataFrame({
    "PCA1": X_pca[:, 0],
    "PCA2": X_pca[:, 1],
    "Cluster": clusters
})

fig = px.scatter(
    df_pca,
    x="PCA1",
    y="PCA2",
    color=df_pca["Cluster"].astype(str),
    title="Agrupación de pacientes mediante PCA y K-Means"
)

fig.write_html("graficas_metabric/13_pca_clusters.html")
fig.show()

"""## 3.14. Gráfica que representa la supervivencia según HER2"""

# =====================================================
# 14. Supervivencia según HER2
# =====================================================

plt.figure(figsize=(8, 6))

sns.boxplot(
    data=df,
    x="HER2 Status",
    y="Overall Survival (Months)"
)

plt.title("Supervivencia global según estado HER2")
plt.xlabel("Estado HER2")
plt.ylabel("Supervivencia global (meses)")
guardar("14_supervivencia_por_her2")

"""## 3.15. Gráfica relacionando supervivencia según ER"""

# =====================================================
# 15. Supervivencia según ER
# =====================================================

plt.figure(figsize=(8, 6))

sns.boxplot(
    data=df,
    x="ER Status",
    y="Overall Survival (Months)"
)

plt.title("Supervivencia global según estado ER")
plt.xlabel("Estado ER")
plt.ylabel("Supervivencia global (meses)")
guardar("15_supervivencia_por_er")

"""## 3.16. Gráfica relacionando supervivencia según PR"""

# =====================================================
# 16. Supervivencia según PR
# =====================================================

plt.figure(figsize=(8, 6))

sns.boxplot(
    data=df,
    x="PR Status",
    y="Overall Survival (Months)"
)

plt.title("Supervivencia global según estado PR")
plt.xlabel("Estado PR")
plt.ylabel("Supervivencia global (meses)")
guardar("16_supervivencia_por_pr")

"""## 3.17. Gráficas (curvas de Kaplan-Meier) por estadio tumoral"""

# =====================================================
# 17. Kaplan-Meier por estadio tumoral
# =====================================================

from lifelines import KaplanMeierFitter

df_km = df[
    [
        "Overall Survival (Months)",
        "Overall Survival Status",
        "Tumor Stage"
    ]
].dropna()

# Crear variable evento: 1 = fallecida, 0 = censurada
df_km["event"] = df_km["Overall Survival Status"].apply(
    lambda x: 1 if "deceased" in str(x).lower() or "died" in str(x).lower() else 0
)

kmf = KaplanMeierFitter()

plt.figure(figsize=(9, 6))

for stage in sorted(df_km["Tumor Stage"].unique()):
    data_stage = df_km[df_km["Tumor Stage"] == stage]

    if len(data_stage) > 10:
        kmf.fit(
            durations=data_stage["Overall Survival (Months)"],
            event_observed=data_stage["event"],
            label=f"Estadio {stage}"
        )
        kmf.plot_survival_function(ci_show=False)

plt.title("Curvas Kaplan-Meier de supervivencia por estadio tumoral")
plt.xlabel("Tiempo de seguimiento (meses)")
plt.ylabel("Probabilidad de supervivencia")
plt.grid(True)
guardar("17_kaplan_meier_estadio")

"""## 3.18. Gráficas (curvas de Kaplan-Meier) por subtipo molecular PAM50"""

# =====================================================
# 18. Kaplan-Meier por subtipo molecular PAM50
# =====================================================

df_km_pam50 = df[
    [
        "Overall Survival (Months)",
        "Overall Survival Status",
        "Pam50 + Claudin-low subtype"
    ]
].dropna()

df_km_pam50["event"] = df_km_pam50["Overall Survival Status"].apply(
    lambda x: 1 if "deceased" in str(x).lower() or "died" in str(x).lower() else 0
)

kmf = KaplanMeierFitter()

plt.figure(figsize=(10, 6))

for subtype in df_km_pam50["Pam50 + Claudin-low subtype"].value_counts().index:
    data_subtype = df_km_pam50[
        df_km_pam50["Pam50 + Claudin-low subtype"] == subtype
    ]

    if len(data_subtype) > 30:
        kmf.fit(
            durations=data_subtype["Overall Survival (Months)"],
            event_observed=data_subtype["event"],
            label=subtype
        )
        kmf.plot_survival_function(ci_show=False)

plt.title("Curvas Kaplan-Meier de supervivencia por subtipo molecular")
plt.xlabel("Tiempo de seguimiento (meses)")
plt.ylabel("Probabilidad de supervivencia")
plt.grid(True)
guardar("18_kaplan_meier_pam50")

"""## 3.19. Gráfica PCA y clustering más completo"""

# =====================================================
# 19. PCA + Clustering más completo
# =====================================================

vars_cluster = [
    "Age at Diagnosis",
    "Tumor Stage",
    "Tumor Size",
    "Mutation Count",
    "Nottingham prognostic index",
    "Lymph nodes examined positive"
]

df_cluster = df[
    vars_cluster +
    [
        "Pam50 + Claudin-low subtype",
        "Relapse Free Status",
        "Overall Survival Status",
        "Overall Survival (Months)"
    ]
].dropna()

X = df_cluster[vars_cluster]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

kmeans = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

df_cluster["Cluster"] = kmeans.fit_predict(X_scaled)
df_cluster["PCA1"] = X_pca[:, 0]
df_cluster["PCA2"] = X_pca[:, 1]

fig = px.scatter(
    df_cluster,
    x="PCA1",
    y="PCA2",
    color=df_cluster["Cluster"].astype(str),
    hover_data=[
        "Age at Diagnosis",
        "Tumor Stage",
        "Tumor Size",
        "Mutation Count",
        "Nottingham prognostic index",
        "Lymph nodes examined positive",
        "Pam50 + Claudin-low subtype",
        "Relapse Free Status",
        "Overall Survival (Months)"
    ],
    title="Perfiles de pacientes mediante PCA y K-Means"
)

fig.write_html("graficas_metabric/19_pca_clusters_completo.html")
fig.show()

"""## 3.20. Gráfica representando la recaída por cluster"""

# =====================================================
# 20. Recaída por cluster
# =====================================================

tabla_cluster_recaida = pd.crosstab(
    df_cluster["Cluster"],
    df_cluster["Relapse Free Status"],
    normalize="index"
) * 100

tabla_cluster_recaida.plot(
    kind="bar",
    stacked=True,
    figsize=(8, 6)
)

plt.title("Porcentaje de recaída por cluster de pacientes")
plt.xlabel("Cluster")
plt.ylabel("Porcentaje de pacientes")
plt.legend(title="Estado de recaída")
guardar("20_recaida_por_cluster")

"""## 3.21. Gráfica representa la supervivencia por cluster"""

# =====================================================
# 21. Supervivencia por cluster
# =====================================================

plt.figure(figsize=(8, 6))

sns.boxplot(
    data=df_cluster,
    x="Cluster",
    y="Overall Survival (Months)"
)

plt.title("Supervivencia global según cluster de pacientes")
plt.xlabel("Cluster")
plt.ylabel("Supervivencia global (meses)")
guardar("21_supervivencia_por_cluster")

"""# 4. Tablas

## 4.1. Tabla caracterización de los clusters
"""

# =====================================================
# 20. Caracterización de los clusters
# =====================================================

resumen_clusters = df_cluster.groupby("Cluster")[vars_cluster + [
    "Overall Survival (Months)"
]].mean().round(2)

print("\nResumen medio de cada cluster:")
print(resumen_clusters)

resumen_clusters.to_csv(
    "tablas_metabric/01_resumen_clusters.csv"
)
